websiteDataVolume:
  image: myown/ubuntu
  volumes:
  - ./src:/var/www/html

sharedDataVolume:
  image: myown/ubuntu
  volumes:
  - ./sharedData:/sharedData/

loadBalancer:
  image: myown/nginx
  ports:
  - "8000:80"
  links:
  - webServerMachine1:docker-web-1.local
  - webServerMachine2:docker-web-2.local
  volumes:
  - ./config/nginx/loadbalancer/nginx.conf:/etc/nginx/nginx.conf
  volumes_from:
  - sharedDataVolume
  - websiteDataVolume
  environment:
     VIRTUAL_HOST: docker-web.local

webServerMachine1:
  image: myown/nginx
  links:
  - phpMachine:docker-php.local
  volumes:
  - ./config/nginx/webserver/default.conf:/etc/nginx/conf.d/default.conf
  volumes_from:
  - sharedDataVolume
  - websiteDataVolume
  environment:
     VIRTUAL_HOST: docker-web-1.local

webServerMachine2:
  image: myown/nginx
  links:
  - phpMachine:docker-php.local
  volumes:
  - ./config/nginx/webserver/default.conf:/etc/nginx/conf.d/default.conf
  volumes_from:
  - sharedDataVolume
  - websiteDataVolume
  environment:
     VIRTUAL_HOST: docker-web-2.local

phpMachine:
  image: myown/php
  links:
  - mariaDBServerMachine:docker-mariadb.local
  - rabbitMQServerMachine:docker-rabbitmq.local
  - mongoDBServerMachine:docker-mongodb.local
  - redisServerMachine:docker-redis.local
  volumes:
  - ./config/php/php.ini:/usr/local/etc/php/php.ini
  volumes_from:
  - sharedDataVolume
  - websiteDataVolume
  environment:
     VIRTUAL_HOST: docker-php.local

mariaDBServerMachine:
  image: mariadb
  volumes_from:
  - sharedDataVolume
  environment:
     VIRTUAL_HOST: docker-mariadb.local
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: docker_sample
     MYSQL_USER:  docker
     MYSQL_PASSWORD:  sample

rabbitMQServerMachine:
  image: rabbitmq:3.6.5-management
  ports:
  - "15672:15672"
  volumes_from:
  - sharedDataVolume
  environment:
     VIRTUAL_HOST: docker-rabbitmq.local

mongoDBServerMachine:
  image: mongo:3.0.13
  volumes_from:
  - sharedDataVolume
  environment:
     VIRTUAL_HOST: docker-mongo.local

redisServerMachine:
  image: redis:3.0.7
  volumes:
  - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
  volumes_from:
  - sharedDataVolume
  environment:
     VIRTUAL_HOST: docker-redis.local